In [12]:
import numpy as np
a = np.array([7,3, 5])
b = np.array([4,2, 5])
print("Original numbers:")
print(a)
print(b)
print("greater")
print(np.greater(a, b))
print("greater_equal")
print(np.greater_equal(a, b))
print("less")
print(np.less(a, b))
print("less_equal")
print(np.less_equal(a, b))

Original numbers:
[7 3 5]
[4 2 5]
greater
[ True  True False]
greater_equal
[ True  True  True]
less
[False False False]
less_equal
[False False  True]


In [3]:
 import numpy as np
x=np.arange(30,71,2)
print("Even integers from 30 to 70")
print(x) 

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [13]:
import numpy as np
id_mat=np.identity(3)
print('Identity matrix:')
print(id_mat)

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
import numpy as np
x = np.arange(21)
print("Initial:")
print(x)
print("Final:")
x[(x >= 9) & (x <= 15)] *= -1
print(x)

Initial:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Final:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [6]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [15]:
import numpy as np
x = np.array([[6,8,1],[4,2,3]])
print("Original :")
print(x)
print("Sum of elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original :
[[6 8 1]
 [4 2 3]]
Sum of elements:
24
Sum of each column:
[10 10  4]
Sum of each row:
[15  9]


In [17]:
import numpy as np
import os
x = np.arange(6).reshape(3, 2)
print("Initial array is:")
print(x)
header = 'col1 col2 col3'
np.savetxt('t.txt', x, fmt="%d", header=header) 
print("Final array is:")
result = np.loadtxt('t.txt')
print(result)

Initial array is:
[[0 1]
 [2 3]
 [4 5]]
Final array is:
[[0. 1.]
 [2. 3.]
 [4. 5.]]


In [18]:
import numpy as np
x = np.array([1,7,8])
print("1st array:")
print(x)
y = np.array([4,2,1])
print("2nd array:")
print(y)
print("after testing")
array_equal = np.allclose(x, y)
print(array_equal)

1st array:
[1 7 8]
2nd array:
[4 2 1]
Testing array equal or not
False


In [27]:
import numpy as np
n = np.arange(16).reshape(-1, 4)
print("Original array:")
print(n)
print("\nafter swapping :")
n[[0,-1],:]=n[[-1,0],:]
print(n)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

after swapping :
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [28]:
import numpy as np 
a = np.array([[1, 3, 2],
              [4, 5, 2],
            [3,8,2]])
b = np.array([[4, 3, 1],
              [3, 4, 5],
              [4,2,1]])
print("1st array:") 
print(a)
print("2nd array:") 
print(b)
print("\nafter multiplication:")
print(np.multiply(a, b))

1st array:
[[1 3 2]
 [4 5 2]
 [3 8 2]]
2nd array:
[[4 3 1]
 [3 4 5]
 [4 2 1]]

after multiplication:
[[ 4  9  2]
 [12 20 10]
 [12 16  2]]
