In [8]:
import numpy as np
R1 = int(input("Enter the no of rows:"))
C1 = int(input("Enter the no of coloumn:"))
print("Enter the entries in a single line(sepearated by space): ")
entries = list(map(int, input().split()))
m1 = np.array(entries).reshape(R1,C1)
print("Matrix_1: \n",m1)


R2 = int(input("Enter the no of rows:"))
C2= int(input("Enter the no of coloumn:"))
print("Enter the entries in a single line(sepearated by space): ")
entries = list(map(int, input().split()))
m2 = np.array(entries).reshape(R2,C2)
print("matrix_2: \n",m2)

Enter the no of rows: 2
Enter the no of coloumn: 2


Enter the entries in a single line(sepearated by space): 


 1 2 3 4


Matrix_1: 
 [[1 2]
 [3 4]]


Enter the no of rows: 2
Enter the no of coloumn: 2


Enter the entries in a single line(sepearated by space): 


 2 3 4 5


matrix_2: 
 [[2 3]
 [4 5]]


In [10]:
#1
print("1.Dot product")
print(np.dot(m1,m2))

1.Dot product
[[10 13]
 [22 29]]


In [13]:
#2
print("2.Transpose")
print("Transpose of matrix1")
print(np.transpose(m1))
print("Transpose of matrix2")
print(np.transpose(m2#Eigen values and eigen vectors

w1, v1 = np.linalg.eig(matrix_1)


print("The eigen values of matrix_1 : \n",w1)
print(" The eigen vectors of matrix_1:\n",v1)

w2 , v2 = np.linalg.eig(matrix_2)

print("The eigen values of matrix_2 : \n",w2)
print(" The eigen vectors of matrix_2:\n",v2)
))


2.Transpose
Transpose of matrix1
[[1 3]
 [2 4]]
Transpose of matrix2
[[2 4]
 [3 5]]


In [16]:
#3
print("3.Trace")
print("Trace of matrix1")
print(np.trace(m1))
print("Trace of matrix2")
print(np.trace(m2))

3.Trace
Trace of matrix1
5
Trace of matrix2
7


In [23]:
#rank
print("4.Rank")
print("The rank of matrix_1 :",np.linalg.matrix_rank(matrix_1),"\nThe rank of matrix_2 :",np.linalg.matrix_rank(matrix_2))


The rank of matrix_1 : 2 
The rank of matrix_2 : 2


In [29]:
#5
print("5.determinent")
print("The determinent of matrix_1 :",int(np.linalg.det(matrix_1)),"\n The determinent of matrix_2 :",int(np.linalg.det(matrix_2)))


5.determinent
The determinent of matrix_1 : -2 
 The determinent of matrix_2 : -2


In [27]:
#Inverse

print("The inverse of matrix_1 : \n",np.linalg.inv(matrix_1),"\n The inverse of matrix_2 : \n",np.linalg.inv(matrix_2))


The inverse of matrix_1 : 
 [[-2.   1. ]
 [ 1.5 -0.5]] 
 The inverse of matrix_2 : 
 [[-3.   2. ]
 [ 2.5 -1.5]]


In [28]:
#Eigen values and eigen vectors

w1, v1 = np.linalg.eig(matrix_1)

#Eigen values and eigen vectors

w1, v1 = np.linalg.eig(matrix_1)


print("The eigen values of matrix_1 : \n",w1)
print(" The eigen vectors of matrix_1:\n",v1)

w2 , v2 = np.linalg.eig(matrix_2)

print("The eigen values of matrix_2 : \n",w2)
print(" The eigen vectors of matrix_2:\n",v2)

print("The eigen values of matrix_1 : \n",w1)
print(" The eigen vectors of matrix_1:\n",v1)

w2 , v2 = np.linalg.eig(matrix_2)

print("The eigen values of matrix_2 : \n",w2)
print(" The eigen vectors of matrix_2:\n",v2)


The eigen values of matrix_1 : 
 [-0.37228132  5.37228132]
 The eigen vectors of matrix_1:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
The eigen values of matrix_2 : 
 [-0.21699057  9.21699057]
 The eigen vectors of matrix_2:
 [[-0.77925158 -0.54107946]
 [ 0.62671124 -0.84097147]]
